{% set version = "0.1-0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mba
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MBA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MBA/MBA_{{ version }}.tar.gz
  sha256: 78039905c5b98be2bb79a5f292187a2aca21ef449daeefea58b0cac53a5283af

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bh
  run:
    - r-base
    #- r-bh

test:
  commands:
    - $R -e "library('MBA')"           # [not win]
    - "\"%R%\" -e \"library('MBA')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MBA
  license: GPL-2.0-or-later
  summary: Functions to interpolate irregularly and regularly spaced data using Multilevel B-spline Approximation (MBA). Functions call portions of the SINTEF Multilevel B-spline Library written by Øyvind Hjelle which implements methods developed by Lee, Wolberg and Shin (1997; <doi:10.1109/2945.620490>).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
