appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: JwZf5AuPEgSY5PWKjrOlgwA4pcyWhV5WvQZ/+5U+U7kskyojicRg8cvTe3vdXWT2VP3M57tFwFlXjG1M4ns2SZoAbYubY3VPcLeqKDthwggVEe5Q6MvgSKbn7wbpua52t+oRakanKak9crPEqik2zcwsPUqwd9JkorxacUzZE3Pmpkl6SjcyjcIeKHoc7J0QpVPa24z+u4zKt41nZT2KyDDXO53ijRPH4Jb0DdPZ+OEJB0SLU173ZZZHxAOfoXbO4Cnj/PeRbhHNvL7Lhkb5GzeBJGfc/0AmxJbHnppOYrEz9DrJHlGRWYHKjefR/KqHb83zA96LY8rYcS+IU8hXu+i9AwxhVIAjk4nIXOH8KJkPPQGQIa25TAgDYnMyoRLFwcdF6b1vOJcTtEo/J4gfAEANsV6zaTclqVFA18JIGQJtjUz0gzjkDrsLAb5gq5wvg/ssUXUdJp15E+qYwQvZbFv/nnStHh+Bt6/cAQo6EPHlQy1c2+1ewlBC96uROEmZNlYGRrBwqP9SfaqqjeSR+TNvytiy8D4ZBUb62DREIJdDE7TQs6mMGIJ3nhXzIL3CrIk1pqb4KuL3zKar7+AlKT1nfyPon5RyloHGoTPJ18RkEPaIA6MPfUdgztRYGVbWxyM8RDbiEHLyaftIJa8ony5r5i8Stdi3nae4SE0avnU=}
